In [1]:
import tensorflow as tf
import keras as keras

In [19]:
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1]
bias = 2
output1 = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias

print(output1)

# employ dot product
import numpy as np

output1 = np.dot(inputs, weights) + bias
print("output from np: ", output1)

4.8
output from np:  4.8


In [20]:
# 4 inputs and 3 neurons
inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5


output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]
          
          

print(output)

[4.8, 1.21, 2.385]
output from np:  4.8


In [22]:
import numpy as np

# Define inputs
inputs = [1, 2, 3, 2.5]

# Define weights for 3 neurons
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

# Define biases for 3 neurons
biases = [2, 3, 0.5]

# Manual calculation (same as your code, just refactored)
output = [inputs[0]*weights[0][0] + inputs[1]*weights[0][1] + inputs[2]*weights[0][2] + inputs[3]*weights[0][3] + biases[0],
          inputs[0]*weights[1][0] + inputs[1]*weights[1][1] + inputs[2]*weights[1][2] + inputs[3]*weights[1][3] + biases[1],
          inputs[0]*weights[2][0] + inputs[1]*weights[2][1] + inputs[2]*weights[2][2] + inputs[3]*weights[2][3] + biases[2]]

print("Manual output:", output)

# Using np.dot() for the same calculation
output_np = np.dot(weights, inputs) + biases
print("Output from np.dot():", output_np)


Manual output: [4.8, 1.21, 2.385]
Output from np.dot(): [4.8   1.21  2.385]


### forward propagation in ANN

In [31]:
import numpy as np

# Generate random weights and biases using numpy's random uniform function
weights = np.around(np.random.uniform(size=6), decimals=4)
biases = np.around(np.random.uniform(size=4), decimals=4)  # Updated to size=4

print("Weights:", weights)
print("Biases:", biases)

# Inputs
x_1 = 0.5
x_2 = 0.85

print("x1 is {} and x2 is {}".format(x_1, x_2))

# Calculate the weighted sum for the first and second nodes in the hidden layer
z_11 = x_1*weights[0] + x_2*weights[1] + biases[0]
print("The weighted sum of the inputs at the first node in the hidden layer is {:.4f}".format(z_11))

z_12 = x_1*weights[2] + x_2*weights[3] + biases[1]
print("The weighted sum of the inputs at the second node in the hidden layer is {:.4f}".format(z_12))

# Assuming a sigmoid activation function, let's compute the activation for both nodes
a_11 = 1 / (1 + np.exp(-z_11))
print("The activation of the first node in the hidden layer is {:.4f}".format(a_11))

a_12 = 1 / (1 + np.exp(-z_12))
print("The activation of the second node in the hidden layer is {:.4f}".format(a_12))

# Compute the weighted sum for the final node using activations and third bias
z_2 = a_11*weights[4] + a_12*weights[5] + biases[2]
print("The weighted sum of the inputs at the final node is {:.4f}".format(z_2))

# output of the network in the output
a_2 = 1/(1 + np.exp(-z_2))
print("The output of the network for X is {:.4f}".format(z_2))

Weights: [0.799  0.4639 0.7279 0.5723 0.719  0.1712]
Biases: [0.7691 0.8852 0.758  0.5268]
x1 is 0.5 and x2 is 0.85
The weighted sum of the inputs at the first node in the hidden layer is 1.5629
The weighted sum of the inputs at the second node in the hidden layer is 1.7356
The activation of the first node in the hidden layer is 0.8268
The activation of the second node in the hidden layer is 0.8501
The weighted sum of the inputs at the final node is 1.4980


In [33]:
import numpy as np

# Define the batches of inputs (3 samples, each with 4 features)
inputs = [[1, 2, 3, 2.5],
          [2, 5, -1, 2],
          [-1.5, 2.7, 3.3, -0.8]]  # Added missing comma here

# Define weights and biases for 3 neurons
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

# Compute the output by performing dot product between inputs and transposed weights
layer_output = np.dot(inputs, np.array(weights).T) + biases
print(layer_output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [34]:
# So far, we have an input layer with 4 features and a hidden layer with 3 neurons
# Add another layer with 3 neurons
weights2 = [[0.1,-0.14,0.5],
           [-0.5, 0.12,-0.33],
           [-0.44,0.73,0.13]]

biases = [2, 3, 0.5]

layer_output2 = np.dot(layer_output, np.array(weights2).T) + biases
print(layer_output2)

[[ 3.5031  -0.04185 -0.41865]
 [ 3.2434  -1.7332  -4.7113 ]
 [ 2.00686  2.41254  0.65021]]
